import type { Product } from '@/types';

const RICE_IMAGE = 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1400&q=85';
const RICE_IMAGE_ALT = 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1400&q=85';
const RICE_IMAGE_DETAIL = 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1400&q=85';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 'fallback-golden-sella-rice',
    name: 'Golden Sella Rice',
    slug: 'golden-sella-rice',
    category: 'Basmati',
    short_description: 'Parboiled golden rice with excellent grain separation and dependable cooking performance.',
    full_description:
      'Golden Sella Rice is a premium parboiled basmati variety selected for its warm golden colour, long slender grains, and reliable separation after cooking. The parboiling process helps the grain retain nutrients and stay firm, making it a dependable choice for high-volume kitchens and wholesale supply.\n\nIt is carefully cleaned, graded, and packed to preserve its aroma and consistency from mill to delivery. The finished rice expands beautifully while holding its shape, so every serving looks generous and polished.',
    main_image: RICE_IMAGE,
    images: [RICE_IMAGE_ALT, RICE_IMAGE_DETAIL],
    video_url: 'https://cdn.coverr.co/videos/coverr-cooking-rice-1575/1080p.mp4',
    price: null,
    wholesale_price: null,
    pack_sizes: ['5 KG', '10 KG', '25 KG', '50 KG'],
    rice_type: 'Parboiled Golden Sella Basmati',
    origin: 'Punjab and Haryana, India',
    grain_length: 'Long grain, 7.1 mm+ raw length',
    aroma: 'Mild, clean basmati aroma',
    texture: 'Firm, fluffy, and non-sticky',
    cooking_info: 'Soak for 20-30 minutes. Cook with 1.5 parts water for every part rice.',
    best_used_for: 'Biryani, pulao, catering, restaurants, and everyday premium meals',
    min_order_quantity: 100,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    seo_title: 'Golden Sella Rice | Wholesale Basmati Supplier',
    seo_description: 'Order premium Golden Sella parboiled basmati rice in wholesale packs from ABD World Rice.',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fallback-premium-basmati-rice',
    name: 'Premium Basmati Rice',
    slug: 'premium-basmati-rice',
    category: 'Basmati',
    short_description: 'Long-grain, naturally aromatic basmati rice selected for consistent wholesale quality.',
    full_description:
      'Premium Basmati Rice is selected for its elegant long grains, delicate aroma, and dependable texture. Each batch is cleaned and graded for uniformity, giving retailers and professional kitchens a reliable product that performs beautifully across everyday meals and celebratory menus.\n\nThe grains lengthen during cooking while staying light and separate. It is a versatile staple for foodservice buyers who need consistent results, attractive presentation, and dependable bulk supply.',
    main_image: RICE_IMAGE_DETAIL,
    images: [RICE_IMAGE, RICE_IMAGE_ALT],
    video_url: 'https://cdn.coverr.co/videos/coverr-cooking-rice-1575/1080p.mp4',
    price: null,
    wholesale_price: null,
    pack_sizes: ['5 KG', '10 KG', '25 KG', '50 KG'],
    rice_type: 'Aged Long-Grain Basmati',
    origin: 'Punjab, India',
    grain_length: 'Long grain, 6.8 mm+ raw length',
    aroma: 'Distinctive floral basmati aroma',
    texture: 'Light, fluffy, and separate',
    cooking_info: 'Rinse twice and soak for 20 minutes before cooking.',
    best_used_for: 'Daily meals, pulao, biryani, catering, and restaurants',
    min_order_quantity: 100,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    seo_title: 'Premium Basmati Rice | Wholesale Supplier',
    seo_description: 'Buy long-grain Premium Basmati Rice in wholesale packs from ABD World Rice.',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fallback-1121-basmati-rice',
    name: '1121 Basmati Rice',
    slug: '1121-basmati-rice',
    category: 'Premium Basmati',
    short_description: 'Extra-long grain basmati with refined aroma and exceptional length after cooking.',
    full_description:
      '1121 Basmati Rice is prized for its exceptional grain length and elegant appearance after cooking. The carefully selected grains expand dramatically without becoming sticky, making this variety a premium choice for biryani houses, hotels, caterers, and export-focused buyers.\n\nIts clean aroma, firm bite, and impressive plate presentation make it a dependable flagship product for businesses that want their rice dishes to stand out.',
    main_image: RICE_IMAGE_ALT,
    images: [RICE_IMAGE_DETAIL, RICE_IMAGE],
    video_url: 'https://cdn.coverr.co/videos/coverr-cooking-rice-1575/1080p.mp4',
    price: null,
    wholesale_price: null,
    pack_sizes: ['5 KG', '10 KG', '25 KG'],
    rice_type: '1121 Extra-Long Grain Basmati',
    origin: 'Haryana and Punjab, India',
    grain_length: 'Extra-long grain, 8.3 mm+ raw length',
    aroma: 'Rich, refined basmati aroma',
    texture: 'Firm, fluffy, and dramatically elongated',
    cooking_info: 'Soak for 30 minutes. Cook gently and rest for 10 minutes before serving.',
    best_used_for: 'Premium biryani, weddings, hotels, banquets, and export orders',
    min_order_quantity: 100,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    seo_title: '1121 Basmati Rice | Extra-Long Grain Wholesale',
    seo_description: 'Source premium 1121 extra-long grain basmati rice in wholesale packs from ABD World Rice.',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
];

export function getFallbackProduct(slug: string) {
  return FALLBACK_PRODUCTS.find((product) => product.slug === slug) ?? null;
}
